CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_nickname UNIQUE (nickname)
);

CREATE TABLE stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    market VARCHAR(10) NOT NULL DEFAULT 'KRX',
    tradable BOOLEAN NOT NULL DEFAULT TRUE,
    price_collection_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stocks PRIMARY KEY (id),
    CONSTRAINT uk_stocks_market_symbol UNIQUE (market, symbol),
    CONSTRAINT ck_stocks_symbol_not_blank CHECK (btrim(symbol) <> ''),
    CONSTRAINT ck_stocks_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_stocks_market_not_blank CHECK (btrim(market) <> '')
);

CREATE INDEX idx_stocks_collection_target
    ON stocks (price_collection_enabled, tradable, id);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    cash_balance NUMERIC(19, 4) NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_accounts_cash_balance_non_negative CHECK (cash_balance >= 0),
    CONSTRAINT ck_accounts_version_non_negative CHECK (version >= 0),
    CONSTRAINT ck_accounts_number_not_blank CHECK (btrim(account_number) <> '')
);

CREATE INDEX idx_accounts_user_id
    ON accounts (user_id);

CREATE TABLE stock_minute_candles (
    stock_id BIGINT NOT NULL,
    candle_time TIMESTAMPTZ NOT NULL,
    open_price NUMERIC(19, 4) NOT NULL,
    high_price NUMERIC(19, 4) NOT NULL,
    low_price NUMERIC(19, 4) NOT NULL,
    close_price NUMERIC(19, 4) NOT NULL,
    volume BIGINT NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'KIS',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stock_minute_candles PRIMARY KEY (stock_id, candle_time),
    CONSTRAINT fk_stock_minute_candles_stock
        FOREIGN KEY (stock_id)
        REFERENCES stocks (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_stock_minute_candles_open_positive CHECK (open_price > 0),
    CONSTRAINT ck_stock_minute_candles_high_positive CHECK (high_price > 0),
    CONSTRAINT ck_stock_minute_candles_low_positive CHECK (low_price > 0),
    CONSTRAINT ck_stock_minute_candles_close_positive CHECK (close_price > 0),
    CONSTRAINT ck_stock_minute_candles_volume_positive CHECK (volume > 0),
    CONSTRAINT ck_stock_minute_candles_high_range CHECK (
        high_price >= open_price
        AND high_price >= low_price
        AND high_price >= close_price
    ),
    CONSTRAINT ck_stock_minute_candles_low_range CHECK (
        low_price <= open_price
        AND low_price <= high_price
        AND low_price <= close_price
    ),
    CONSTRAINT ck_stock_minute_candles_source_not_blank CHECK (btrim(source) <> '')
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_order_id VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    side VARCHAR(4) NOT NULL,
    order_type VARCHAR(10) NOT NULL DEFAULT 'MARKET',
    status VARCHAR(16) NOT NULL,
    requested_quantity BIGINT NOT NULL,
    executed_quantity BIGINT NOT NULL DEFAULT 0,
    execution_price NUMERIC(19, 4),
    total_amount NUMERIC(19, 4),
    fee NUMERIC(19, 4) NOT NULL DEFAULT 0,
    tax NUMERIC(19, 4) NOT NULL DEFAULT 0,
    rejection_code VARCHAR(40),
    rejection_reason VARCHAR(255),
    quote_market_time TIMESTAMPTZ,
    quote_received_at TIMESTAMPTZ,
    ordered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    executed_at TIMESTAMPTZ,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uk_orders_account_client_order UNIQUE (account_id, client_order_id),
    CONSTRAINT fk_orders_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_stock
        FOREIGN KEY (stock_id)
        REFERENCES stocks (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_orders_client_order_id_not_blank CHECK (btrim(client_order_id) <> ''),
    CONSTRAINT ck_orders_side CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_orders_type CHECK (order_type = 'MARKET'),
    CONSTRAINT ck_orders_status CHECK (status IN ('EXECUTED', 'REJECTED')),
    CONSTRAINT ck_orders_requested_quantity_positive CHECK (requested_quantity > 0),
    CONSTRAINT ck_orders_executed_quantity_non_negative CHECK (executed_quantity >= 0),
    CONSTRAINT ck_orders_execution_price_positive CHECK (
        execution_price IS NULL OR execution_price > 0
    ),
    CONSTRAINT ck_orders_total_amount_positive CHECK (
        total_amount IS NULL OR total_amount > 0
    ),
    CONSTRAINT ck_orders_fee_non_negative CHECK (fee >= 0),
    CONSTRAINT ck_orders_tax_non_negative CHECK (tax >= 0),
    CONSTRAINT ck_orders_result_consistency CHECK (
        (
            status = 'EXECUTED'
            AND executed_quantity = requested_quantity
            AND execution_price IS NOT NULL
            AND total_amount IS NOT NULL
            AND quote_market_time IS NOT NULL
            AND quote_received_at IS NOT NULL
            AND executed_at IS NOT NULL
            AND rejection_code IS NULL
            AND rejection_reason IS NULL
        )
        OR
        (
            status = 'REJECTED'
            AND executed_quantity = 0
            AND execution_price IS NULL
            AND total_amount IS NULL
            AND executed_at IS NULL
            AND rejection_code IS NOT NULL
        )
    )
);

CREATE INDEX idx_orders_account_ordered
    ON orders (account_id, ordered_at DESC, id DESC);

CREATE INDEX idx_orders_stock_ordered
    ON orders (stock_id, ordered_at DESC, id DESC);

CREATE INDEX idx_orders_status_ordered
    ON orders (status, ordered_at DESC, id DESC);

CREATE TABLE holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL DEFAULT 0,
    average_price NUMERIC(19, 4) NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_holdings PRIMARY KEY (id),
    CONSTRAINT uk_holdings_account_stock UNIQUE (account_id, stock_id),
    CONSTRAINT fk_holdings_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_holdings_stock
        FOREIGN KEY (stock_id)
        REFERENCES stocks (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_holdings_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT ck_holdings_average_price_non_negative CHECK (average_price >= 0),
    CONSTRAINT ck_holdings_version_non_negative CHECK (version >= 0),
    CONSTRAINT ck_holdings_empty_average_price CHECK (
        (quantity = 0 AND average_price = 0)
        OR (quantity > 0 AND average_price > 0)
    )
);

CREATE INDEX idx_holdings_stock_id
    ON holdings (stock_id);

CREATE TABLE account_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    order_id BIGINT,
    type VARCHAR(16) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    balance_after NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_account_transactions PRIMARY KEY (id),
    CONSTRAINT fk_account_transactions_account
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_account_transactions_type CHECK (
        type IN ('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL')
    ),
    CONSTRAINT ck_account_transactions_amount_not_zero CHECK (amount <> 0),
    CONSTRAINT ck_account_transactions_balance_non_negative CHECK (balance_after >= 0),
    CONSTRAINT ck_account_transactions_order_presence CHECK (
        (type IN ('BUY', 'SELL') AND order_id IS NOT NULL)
        OR (type IN ('DEPOSIT', 'WITHDRAWAL') AND order_id IS NULL)
    ),
    CONSTRAINT ck_account_transactions_amount_direction CHECK (
        (type IN ('DEPOSIT', 'SELL') AND amount > 0)
        OR (type IN ('WITHDRAWAL', 'BUY') AND amount < 0)
    )
);

CREATE INDEX idx_account_transactions_account_created
    ON account_transactions (account_id, created_at DESC, id DESC);

CREATE INDEX idx_account_transactions_order_id
    ON account_transactions (order_id)
    WHERE order_id IS NOT NULL;

CREATE TABLE holding_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    holding_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    type VARCHAR(4) NOT NULL,
    quantity_change BIGINT NOT NULL,
    quantity_after BIGINT NOT NULL,
    execution_price NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_holding_transactions PRIMARY KEY (id),
    CONSTRAINT fk_holding_transactions_holding
        FOREIGN KEY (holding_id)
        REFERENCES holdings (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_holding_transactions_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_holding_transactions_type CHECK (type IN ('BUY', 'SELL')),
    CONSTRAINT ck_holding_transactions_quantity_after_non_negative CHECK (quantity_after >= 0),
    CONSTRAINT ck_holding_transactions_execution_price_positive CHECK (execution_price > 0),
    CONSTRAINT ck_holding_transactions_quantity_direction CHECK (
        (type = 'BUY' AND quantity_change > 0)
        OR (type = 'SELL' AND quantity_change < 0)
    )
);

CREATE INDEX idx_holding_transactions_holding_created
    ON holding_transactions (holding_id, created_at DESC, id DESC);

CREATE INDEX idx_holding_transactions_order_id
    ON holding_transactions (order_id);
