CREATE TABLE authentication_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    attempted_email VARCHAR(255) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    user_agent VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_authentication_events PRIMARY KEY (id),
    CONSTRAINT fk_authentication_events_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE SET NULL,
    CONSTRAINT ck_authentication_events_outcome CHECK (
        outcome IN ('SUCCEEDED', 'FAILED', 'RATE_LIMITED')
    ),
    CONSTRAINT ck_authentication_events_email_not_blank CHECK (btrim(attempted_email) <> ''),
    CONSTRAINT ck_authentication_events_ip_not_blank CHECK (btrim(ip_address) <> '')
);

CREATE INDEX idx_auth_events_email_outcome_created
    ON authentication_events (attempted_email, outcome, created_at DESC);

CREATE INDEX idx_auth_events_ip_outcome_created
    ON authentication_events (ip_address, outcome, created_at DESC);

CREATE INDEX idx_auth_events_user_created
    ON authentication_events (user_id, created_at DESC)
    WHERE user_id IS NOT NULL;
