ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE account_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_account_tokens PRIMARY KEY (id),
    CONSTRAINT fk_account_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_account_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_account_tokens_type CHECK (
        type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')
    ),
    CONSTRAINT ck_account_tokens_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_account_tokens_consumed CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE UNIQUE INDEX uk_account_tokens_active_user_type
    ON account_tokens (user_id, type)
    WHERE consumed_at IS NULL;

CREATE INDEX idx_account_tokens_expiry
    ON account_tokens (expires_at)
    WHERE consumed_at IS NULL;
