CREATE TABLE password_reset_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_password_reset_attempts PRIMARY KEY (id),
    CONSTRAINT ck_password_reset_attempts_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_password_reset_attempts_ip_not_blank CHECK (btrim(ip_address) <> '')
);

CREATE INDEX idx_password_reset_attempts_email_created
    ON password_reset_attempts (email, created_at DESC);

CREATE INDEX idx_password_reset_attempts_ip_created
    ON password_reset_attempts (ip_address, created_at DESC);
